_prefs: 
  mapid: james-lane-conkling.5630f970
  saveCenter: true
_properties: {}
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 35.766
  - 36.8818
  - 8
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
name: Safari
source: "mapbox:///mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v5,crowdcover.efad3d99"
styles: 
  - style.mss
  - water.mss
  - terrain.mss
  - road.mss
template: ''
