_prefs: 
  mapid: null
  saveCenter: true
_properties: {}
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 17.6774
  - 43.5103
  - 14
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: 
  - contour.line
  - landcover
  - slope
  - hillshade
  - landuse
  - waterway.casing
  - waterway.fill
  - water
  - aeroway
  - barrier_line
  - building
  - landuse_overlay
  - tunnel
  - road
  - bridge
  - admin
  - contour.label
  - country_label_line
  - country_label
  - state_label
  - place_label
  - water_label
  - road_label
  - waterway_label
  - poi_label
maxzoom: 22
minzoom: 0
name: F64
source: "mapbox:///mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6,james-lane-conkling.ce100e12"
styles: 
  - style.mss
  - water.mss
  - terrain.mss
  - road.mss
  - landuse.mss
  - place.mss
template: ''
